### ISSUE TITLE
Use GTE instead of EQ on the EMI requirement

### ISSUE THREAD

**Issue by roridev** [blocovermelho/ae2-emi-crafting#1]
The FMJ requires EMI based on the gradle property, which is nice but it matches a version specifically, which means that once EMI updates the mod will send a conflict to fabric loader.

Since for whatever reason i released 1.0 and noticed it afterwards, i'll just fix that and use it on the next release.

**Comment by LoboMetalurgico** [comment]
@roridev close this issue

**Comment by roridev** [comment]
oh thanks
