### ISSUE TITLE
Backport Oficial EMI Integration to 1.20.1

### ISSUE THREAD

**Issue by roridev** [blocovermelho/ae2-emi-crafting#13]
Since of https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/7509 EMI is natively supported on 1.20.2+ which limits this mod to 1.20.1 and (maybe) previous versions.

This is an issue containing all of the issues and pull requests related to this process.

- #12
- #14 
- #15

**Comment by roridev** [comment]
Backporting their crafting handling
![image](https://github.com/blocovermelho/ae2-emi-crafting/assets/36565196/2b4524d6-08d5-4630-8b48-2f472826f1d5)
![image](https://github.com/blocovermelho/ae2-emi-crafting/assets/36565196/13ece270-10af-4ccc-b762-c9e8d6468206)

**Comment by roridev** [comment]
Fixed
---
Dev: 4eb03e3
MR: [1.3.0](https://modrinth.com/mod/ae2-emi-crafting/version/1.3.0)
CF: Still Blocked.

**Comment by T0pN1ck** [comment]
gj
