### ISSUE TITLE
Clicking "Fill recipe" doesn't close after filling 

### ISSUE THREAD

**Issue by roridev** [blocovermelho/ae2-emi-crafting#4]

**Comment by T0pN1ck** [comment]
decided that?

**Comment by roridev** [comment]
Fixed
--- 
Dev : 68e00a301c40c48c9273af61e7436791fcbb70b0
Modrinth : [1.2.0](https://modrinth.com/mod/ae2-emi-crafting/version/1.2.0)
CurseForge: Blocked
